---
- name: Find absolute path to systemd-inhibit
  shell: # noqa 305 we need shell as this sets up the path's correctly
    cmd: which systemd-inhibit
  register: which_system_inhibit
  changed_when: False
- name: Ensure borgmatic service override directory exists
  file:
    path: /etc/systemd/system/borgmatic.service.d
    state: directory
    owner: root
    group: root
    mode: '0755'
- name: Install borgmatic systemd unit override file
  template:
    src: "{{ item }}"
    dest: /etc/systemd/system/borgmatic.service.d/override.conf
    mode: '0644'
  with_first_found:
    - "borgmatic-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.service-override.j2"
    - "borgmatic-{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.service-override.j2"
    - "borgmatic.service-override.j2"
- name: Ensure borgmatic timer override directory exists
  file:
    path: /etc/systemd/system/borgmatic.timer.d
    state: directory
    owner: root
    group: root
    mode: '0755'
- name: Install borgmatic systemd timer override file
  template:
    src: borgmatic.timer-override.j2
    dest: /etc/systemd/system/borgmatic.timer.d/override.conf
    mode: '0644'
- name: Make sure borgmatic timer is running
  systemd:
    name: borgmatic.timer
    daemon_reload: true
    state: restarted
    enabled: yes
