---
- name: install borgmatic systemd unit file
  template:
    src: "{{ item }}"
    dest: /etc/systemd/system/borgmatic.service
  with_first_found:
    - "borgmatic-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.service.j2"
    - "borgmatic-{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.service.j2"
    - "borgmatic.service.j2"
- name: install borgmatic systemd timer file
  template:
    src: borgmatic.timer.j2
    dest: /etc/systemd/system/borgmatic.timer
- name: Make sure borgmatic timer is running
  systemd:
    name: borgmatic.timer
    state: started
    enabled: yes
