---
- name: Update apt cache.
  apt:
    update_cache: yes
    cache_valid_time: 3600
- name: Install borg
  import_tasks: borg-install.yml
- name: Install borgmatic
  import_tasks: borgmatic-install.yml
- name: Install bogmatic config files
  import_tasks: borgmatic-config.yml
- name: Install sysctl jobs
  import_tasks: borgmatic-job.yml
- name: Install suspend script
  import_tasks: suspend-script.yml
