---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  tasks:
  - name: register borgbackup version
    command: borg --version
    register: borgbbackup_version_cmd
  - name: borgbackup should be at least 1.1.x
    assert:
      that:
        - "{{ borgbbackup_version_cmd.stdout|regex_replace('borg\\w*\\s+(.*)', '\\1') is version('1.1.0', '>=') }}"
  - name: register borgmatic version
    command: borgmatic --version
    register: borgbmatic_version_cmd
  - name: borgmatic should be at least 1.5.x
    assert:
      that:
        - "{{ borgbmatic_version_cmd.stdout is version('1.5.0', '>=') }}"
  - name: register borgmatic list
    command: borgmatic list
    register: borgmatic_list_cmd
    become: yes
  - name: borgbackup list should contain both repos
    assert:
      that:
        - "{{ borgmatic_list_cmd.stdout is search('/srv/backup_etc: Listing archives') }}"
        - "{{ borgmatic_list_cmd.stdout is search('/srv/backup_home: Listing archives') }}"
