---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  tasks:
  - name: register borgbackup version
    command: borg --version
    register: borgbbackup_version_cmd
  - name: borgbackup should be at least 1.1.x
    assert:
      that:
        - "{{ borgbbackup_version_cmd.stdout|regex_replace('borg\\w*\\s+(.*)', '\\1') is version('1.1.0', '>=') }}"
